services:
    grunch_mercadopago:
        class: Grunch\MercadopagoBundle\Factory
        arguments:
            - %grunch_mercadopago.client_id%
            - %grunch_mercadopago.client_secret%
            - %grunch_mercadopago.sandbox%
