services:
    fabilocky_mercadopago:
        class: Fabilocky\MercadopagoBundle\Factory
        arguments:
            - %fabilocky_mercadopago.client_id%
            - %fabilocky_mercadopago.client_secret%
            - %fabilocky_mercadopago.sandbox%
